### ISSUE TITLE
feat req: firefox support

### ISSUE THREAD

**Issue by DavidBonelo** [alexay7/jpdb-production#1]
それだけ 🙃

**Comment by DavidBonelo** [comment]
alex no seas perro, cómo la vas a hacer solo para chrome jaja

**Comment by ArmoryFou** [comment]
@DavidBonelo ¿Aún la quieres?

**Comment by DavidBonelo** [comment]
sí porfa, sólo abro chromium para hacer las reviews :PensiveUltraGiga:
> pd: ahora eres colaborador @ArmoryFou :0

**Comment by DavidBonelo** [comment]
agradecido con los de arriba :kneeling_man:
